name: delivery
description: Essentials and food ordering.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.4.4+3
  fluttertoast: ^4.0.1
  firebase_database: ^3.1.5
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.6+4
  razorpay_flutter: ^1.2.1
  flutter_open_whatsapp: ^0.1.2
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.10
  after_layout: ^1.0.7+2
  flutter_automation: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/hello.png
    - images/welcome_image.png
    - images/shubh.jpg
    - images/user.png
    - images/logo_axact.png
    - images/axact2.png
    - images/web-development.png
    - images/Logo.png
  fonts:
    - family: sf_pro
      fonts:
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
    - family: Varela_Round
      fonts:
        - asset: fonts/Varela_Round/VarelaRound-Regular.ttf
